---
# Keep the default Vagrant SSH key. It's publicly available and thus
# "insecure", but these VMs aren't for production use and having a well-known
# key allows for easy automation and documentation.
ssh:
  insert_key: false

vms:

  # NOTE: All `box:` declarations in this example point to vagrantcloud.com
  # and require Vagrant 1.5.0 or newer to function.
  - name: pe-201620-master
    debug-kit: true
    box: puppetlabs/centos-6.6-64-nocm
    providers:
      - type: vsphere
        template_name: 'templates/centos-6-x86_64'
      - type: openstack
        image: 'centos_6_x86_64'
    roles:
      - pe-forward-console
      - pe-memory-tuning2
      - el-stop-firewall
      - el-fix-path
      - 2gb-memory
      - base

  - name: pe-385-master
    debug-kit: true
    box: puppetlabs/centos-6.6-64-nocm
    providers:
      - type: vsphere
        template_name: 'templates/centos-6-x86_64'
      - type: openstack
        image: 'centos_6_x86_64'
    roles:
      - pe-forward-console
      - pe-memory-tuning
      - el-stop-firewall
      - el-fix-path
      - 2gb-memory
      - base

  - name: pe-385-agent
    debug-kit: true
    box: puppetlabs/centos-6.6-64-nocm
    providers:
      - type: vsphere
        template_name: 'templates/centos-6-x86_64'
      - type: openstack
        image: 'centos_6_x86_64'
    roles:
      - el-stop-firewall
      - el-fix-path
      - base

# vim: set ft=yaml:
